name: linux-x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        # - {
        #     name: "x64-ubuntu16.04-gcc release",
        #     arch: x64,
        #     os: ubuntu-16.04,
        #     cc: gcc,
        #     build_type: Release
        #   }
        - {
            name: "x64-ubuntu18.04-gcc release",
            arch: x64,
            os: ubuntu-18.04,
            cc: gcc,
            build_type: Release
          }
        - {
            name: "x64-ubuntu20.04-gcc release",
            arch: x64,
            os: ubuntu-20.04,
            cc: gcc,
            build_type: Release
          }
        - {
            name: "x64-ubuntu20.04-clang release",
            arch: x64,
            os: ubuntu-20.04,
            cc: clang,
            build_type: Release
          }

    steps:
      - uses: actions/checkout@v2

      # static library
      - name: configure-static
        env:
          CC: ${{matrix.config.cc}}
        run: |
          mkdir build-static
          cd build-static
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DBUILD_STATIC=ON -DBUILD_SHARED=OFF -DUSE_ASAN=ON

      - name: build-static
        run: cd build-static && make -j VERBOSE=1
      
      - name: test-static
        run: cd build-static && make test

      # shared library
      - name: configure-shared
        env:
          CC: ${{matrix.config.cc}}
        run: |
          mkdir build-shared
          cd build-shared
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DBUILD_STATIC=OFF -DBUILD_SHARED=ON -DUSE_ASAN=ON

      - name: build-shared
        run: cd build-shared && make -j VERBOSE=1

      - name: test-shared
        run: cd build-shared && make test

      # shared library no asm
      - name: configure-shared-no-asm
        env:
          CC: ${{matrix.config.cc}}
        run: |
          mkdir build-shared-no-asm
          cd build-shared-no-asm
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DBUILD_STATIC=OFF -DBUILD_SHARED=ON -DUSE_ASAN=ON -DUSE_ASM=OFF

      - name: build-shared-no-asm
        run: cd build-shared-no-asm && make -j VERBOSE=1

      - name: test-shared-no-asm
        run: cd build-shared-no-asm && make test
