name: windows-x64-vs2019

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-vs2015:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    # static library
    - name: build-static
      run: |
        mkdir build-static
        cd build-static
        cmake -DBUILD_STATIC=ON -DBUILD_SHARED=OFF ..
        cmake --build . --config Release -j
    - name: test-static
      run: cd build-static; ctest -C Release --output-on-failure

    # shared library
    - name: build-shared
      run: |
        mkdir build-shared
        cd build-shared
        cmake -DBUILD_STATIC=OFF -DBUILD_SHARED=ON ..
        cmake --build . --config Release -j
    - name: test-shared
      run: cd build-shared; ctest -C Release --output-on-failure

    # shared library no asm
    - name: build-shared-no-asm
      run: |
        mkdir build-shared-no-asm
        cd build-shared-no-asm
        cmake -DBUILD_STATIC=OFF -DBUILD_SHARED=ON -DUSE_ASM=OFF ..
        cmake --build . --config Release -j
    - name: test-shared-no-asm
      run: cd build-shared-no-asm; ctest -C Release --output-on-failure
