sudo: required
language: c
compiler: gcc
dist: xenial
notifications:
  email: false

script:
    - mkdir build
    - cd build 
    - cmake ../
    - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
